model: boltz2

# Logical dataset name
dataset: AAV

# Directories are templates that depend on `dataset`
input_dir: "./dataset/input/boltz/AAV"
output_dir: "./output/boltz-2/AAV"

diffusion_samples: 5
seeds: [101]

gpus: [1]
num_gpus: 1

use_potentials: True
cache: "./pretrained_model"  # Path to the cache directory
checkpoint: false

gamma_0: 0.8
noise_scale: 1.003
step_scale: 1.5
sampling_steps: 200

# pdb_id_list: "./evaluation/aggregate_input/AAV/pdb_id_list.txt"
