model: boltz1

# Logical dataset name
dataset: AAV

# Directories are templates that depend on `dataset`
input_dir: "./dataset/input/boltz/AAV"
output_dir: "./output/boltz-gs/AAV"

diffusion_samples: 5
seeds: [101]

gpus: [1]
num_gpus: 1

use_potentials: False
cache: false
checkpoint: ./pretrained_model/last.ckpt

gamma_0: 0.0
noise_scale: 1.0
step_scale: 1.0
sampling_steps: 2