model: boltz1

# Logical dataset name
dataset: AF3_AB

# Directories are templates that depend on `dataset`
input_dir: "./dataset/input/boltz/AF3_AB"
output_dir: "./output/boltz-1/AF3_AB_DEBUG"

diffusion_samples: 10
seeds: [101]

gpus: [1, 2]
num_gpus: 2

use_potentials: false
cache: false
checkpoint: false

gamma_0: 0.605
noise_scale: 0.901
step_scale: 1.638
sampling_steps: 200

pdb_id_list: "./evaluation/aggregate_input/AF3_AB/pdb_id_list.txt"
